
export  const ClubAStructureData = [
    {
        id:1,
        centerImage:'/yellow.png',
        orangeImage:'/orange.png',
        sil1Image:'/silver.png',
        sil2Image:'/silver.png'
    },
    {
        id:2,
        centerImage:'/yellow.png',
        orangeImage:'/orange.png',
        sil1Image:'/silver.png',
        sil2Image:'/silver.png'
    },
    {
        id:3,
        centerImage:'/yellow.png',
        orangeImage:'/orange.png',
        sil1Image:'/silver.png',
        sil2Image:'/silver.png'
    },
    {
        id:4,
        centerImage:'/yellow.png',
        orangeImage:'/orange.png',
        sil1Image:'/silver.png',
        sil2Image:'/silver.png'
    },
    {
        id:5,
        centerImage:'/yellow.png',
        orangeImage:'/orange.png',
        sil1Image:'/silver.png',
        sil2Image:'/silver.png'
    },
    {
        id:6,
        centerImage:'/yellow.png',
        orangeImage:'/orange.png',
        sil1Image:'/silver.png',
        sil2Image:'/silver.png'
    },  {
        id:7,
        centerImage:'/yellow.png',
        orangeImage:'/orange.png',
        sil1Image:'/silver.png',
        sil2Image:'/silver.png'
    },
    {
        id:8,
        centerImage:'/yellow.png',
        orangeImage:'/orange.png',
        sil1Image:'/silver.png',
        sil2Image:'/silver.png'
    },
    {
        id:9,
        centerImage:'/yellow.png',
        orangeImage:'/orange.png',
        sil1Image:'/silver.png',
        sil2Image:'/silver.png'
    },
    {
        id:10,
        centerImage:'/yellow.png',
        orangeImage:'/orange.png',
        sil1Image:'/silver.png',
        sil2Image:'/silver.png'
    },


]