import React from "react";
import "./treePositionStyle.css";

interface treePositionType {
  divStyle: string;
  top?: string;
  right?: string;
  bottom?: string;
  left?: string;
  imgStyle: string;
  imgHeight: number;
  imgWidth: number;
  emptyStyle?: string;
  emptyHeight?: number;
  emptyWidth?: number;
  svgHeight?: string;
  svgWidth?: string;
  mobilesvgHeight?: string;
  mobilesvgWidth?: string;
}

export const treePositionData: treePositionType[] = [
  {
    divStyle: "absolute top-[32%] right-[47%]  w-fit",
    top: "34%",
    right: "47.5%",
    imgStyle: "img-responsive1",
    imgHeight: 25,
    imgWidth: 255,
    emptyHeight: 37,
    emptyWidth: 37,
    svgHeight: "38px",
    svgWidth: "46px",
    mobilesvgHeight: "18px",
    mobilesvgWidth: "27px",
  },
  {
    divStyle: "absolute bottom-[32%] right-[54%]  w-fit",
    bottom: "34%",
    right: "47.5%",
    imgStyle: "img-responsive1",
    imgHeight: 30,
    imgWidth: 30,
    emptyHeight: 22,
    emptyWidth: 32,
    svgHeight: "38px",
    svgWidth: "46px",
    mobilesvgHeight: "18px",
    mobilesvgWidth: "27px",
  },

  // level 2

  {
    divStyle: "absolute ",
    top: "34%",
    left: "38%",
    imgStyle: "img-responsiveTw",
    imgHeight: 27,
    imgWidth: 27,
    emptyHeight: 22,
    emptyWidth: 22,
    svgHeight: "32px",
    svgWidth: "39px",
    mobilesvgHeight: "14px",
    mobilesvgWidth: "22px",
  },

  {
    divStyle: "absolute ",
    top: "34%",
    right: "38%",
    imgStyle: "img-responsiveTw",
    imgHeight: 27,
    imgWidth: 27,
    emptyHeight: 22,
    emptyWidth: 22,
    svgHeight: "32px",
    svgWidth: "39px",
    mobilesvgHeight: "14px",
    mobilesvgWidth: "22px",
  },

  {
    divStyle: "absolute bottom-[29%] left-[33%] ",
    bottom: "33%",
    left: "38%",
    imgStyle: "img-responsiveTw",
    imgHeight: 27,
    imgWidth: 27,
    emptyHeight: 22,
    emptyWidth: 22,
    svgHeight: "32px",
    svgWidth: "39px",
    mobilesvgHeight: "14px",
    mobilesvgWidth: "22px",
  },

  {
    divStyle: "absolute bottom-[29%] right-[34%]",
    bottom: "33%",
    right: "38%",
    imgStyle: "img-responsiveTw",
    imgHeight: 27,
    imgWidth: 27,
    emptyHeight: 22,
    emptyWidth: 22,
    svgHeight: "30px",
    svgWidth: "38px",
    mobilesvgHeight: "14px",
    mobilesvgWidth: "22px",
  },

  // level3
  {
    divStyle: "absolute top-[34%] left-[19%] ",
    top: "38%",
    left: "31%",
    imgStyle: "img-responsiveM",
    imgHeight: 25,
    imgWidth: 25,
    emptyHeight: 30,
    emptyWidth: 28,
    svgHeight: "25px",
    svgWidth: "33px",
    mobilesvgHeight: "12px",
    mobilesvgWidth: "19px",
  },

  {
    divStyle: "absolute top-[18%] left-[37%]",
    top: "25%",
    left: "41%",
    imgStyle: "img-responsiveM",
    imgHeight: 25,
    imgWidth: 25,
    emptyHeight: 30,
    emptyWidth: 28,
    svgHeight: "25px",
    svgWidth: "33px",
    mobilesvgHeight: "12px",
    mobilesvgWidth: "19px",
  },
  {
    divStyle: "absolute top-[18%] right-[37%]",
    top: "25%",
    right: "41%",
    imgStyle: "img-responsiveM",
    imgHeight: 25,
    imgWidth: 25,
    emptyHeight: 30,
    emptyWidth: 28,
    svgHeight: "25px",
    svgWidth: "33px",
    mobilesvgHeight: "12px",
    mobilesvgWidth: "19px",
  },

  {
    divStyle: "absolute top-[34%] right-[20%] ",
    top: "38%",
    right: "31%",
    imgStyle: "img-responsiveM",
    imgHeight: 25,
    imgWidth: 25,
    emptyHeight: 30,
    emptyWidth: 28,
    svgHeight: "25px",
    svgWidth: "33px",
    mobilesvgHeight: "12px",
    mobilesvgWidth: "19px",
  },

  {
    divStyle: "absolute bottom-[35%] left-[19%] ",
    bottom: "38%",
    left: "31%",
    imgStyle: "img-responsiveM",
    imgHeight: 25,
    imgWidth: 25,
    emptyHeight: 30,
    emptyWidth: 28,
    svgHeight: "25px",
    svgWidth: "33px",
    mobilesvgHeight: "12px",
    mobilesvgWidth: "19px",
  },

  {
    divStyle: "absolute bottom-[19%] left-[37%]",
    bottom: "25%",
    left: "41%",
    imgStyle: "img-responsiveM",
    imgHeight: 25,
    imgWidth: 25,
    emptyHeight: 30,
    emptyWidth: 28,
    svgHeight: "25px",
    svgWidth: "33px",
    mobilesvgHeight: "12px",
    mobilesvgWidth: "19px",
  },
  {
    divStyle: "absolute bottom-[19%] right-[37%]",
    bottom: "25%",
    right: "41%",
    imgStyle: "img-responsiveM",
    imgHeight: 25,
    imgWidth: 25,
    emptyHeight: 30,
    emptyWidth: 28,
    svgHeight: "25px",
    svgWidth: "33px",
    mobilesvgHeight: "12px",
    mobilesvgWidth: "19px",
  },

  {
    divStyle: "absolute bottom-[35%] right-[19%] ",
    bottom: "38%",
    right: "31%",
    imgStyle: "img-responsiveM",
    imgHeight: 25,
    imgWidth: 25,
    emptyHeight: 30,
    emptyWidth: 28,
    svgHeight: "25px",
    svgWidth: "33px",
    mobilesvgHeight: "12px",
    mobilesvgWidth: "19px",
  },

  // level4

  {
    divStyle: "absolute top-[39%] left-[9%]",
    top: "41%",
    left: "26.4%",
    imgStyle: "img-responsive",
    imgHeight: 25,
    imgWidth: 25,
    emptyHeight: 30,
    emptyWidth: 28,
    svgHeight: "22px",
    svgWidth: "29px",
    mobilesvgHeight: "9px",
    mobilesvgWidth: "17px",
  },

  {
    divStyle: "absolute top-[25%] left-[15%] ",
    top: "30%",
    left: "29.5%",
    imgStyle: "img-responsive",
    imgHeight: 25,
    imgWidth: 25,
    emptyStyle: "emptyStyle4",
    svgHeight: "22px",
    svgWidth: "29px",
    mobilesvgHeight: "9px",
    mobilesvgWidth: "17px",
  },

  {
    divStyle: "absolute top-[15%] left-[25%]",
    top: "22%",
    left: "36%",
    imgStyle: "img-responsive",
    imgHeight: 25,
    imgWidth: 25,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "22px",
    svgWidth: "29px",
    mobilesvgHeight: "9px",
    mobilesvgWidth: "17px",
  },

  {
    divStyle: "absolute top-[9%] left-[41%]  ",
    top: "17%",
    left: "44%",
    imgStyle: "img-responsive",
    imgHeight: 25,
    imgWidth: 25,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "22px",
    svgWidth: "29px",
    mobilesvgHeight: "9px",
    mobilesvgWidth: "17px",
  },

  {
    divStyle: "absolute top-[9%] right-[41%] ",
    top: "17%",
    right: "44%",
    imgStyle: "img-responsive",
    imgHeight: 25,
    imgWidth: 25,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "22px",
    svgWidth: "29px",
    mobilesvgHeight: "9px",
    mobilesvgWidth: "17px",
  },

  {
    divStyle: "absolute top-[15%] right-[27%]",
    top: "22%",
    right: "36%",
    imgStyle: "img-responsive",
    imgHeight: 25,
    imgWidth: 25,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "22px",
    svgWidth: "29px",
    mobilesvgHeight: "9px",
    mobilesvgWidth: "17px",
  },

  {
    divStyle: "absolute top-[25%] right-[16%] ",
    top: "31%",
    right: "30%",
    imgStyle: "img-responsive",
    imgHeight: 25,
    imgWidth: 25,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "22px",
    svgWidth: "29px",
    mobilesvgHeight: "9px",
    mobilesvgWidth: "17px",
  },

  {
    divStyle: "absolute top-[38%] right-[10%]",
    top: "41%",
    right: "27%",
    imgStyle: "img-responsive",
    imgHeight: 25,
    imgWidth: 25,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "22px",
    svgWidth: "29px",
    mobilesvgHeight: "9px",
    mobilesvgWidth: "17px",
  },

  {
    divStyle: "absolute bottom-[39%] left-[9%]",
    bottom: "41%",
    left: "26.4%",
    imgStyle: "img-responsive",
    imgHeight: 25,
    imgWidth: 25,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "22px",
    svgWidth: "29px",
    mobilesvgHeight: "9px",
    mobilesvgWidth: "17px",
  },
  {
    divStyle: "absolute bottom-[25%] left-[15%] ",
    bottom: "30%",
    left: "29.5%",
    imgStyle: "img-responsive",
    imgHeight: 25,
    imgWidth: 25,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "22px",
    svgWidth: "29px",
    mobilesvgHeight: "9px",
    mobilesvgWidth: "17px",
  },



  {
    divStyle: "absolute bottom-[9%] left-[41%]",
    bottom: "22%",
    left: "36%",
    imgStyle: "img-responsive",
    imgHeight: 25,
    imgWidth: 25,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "22px",
    svgWidth: "29px",
    mobilesvgHeight: "9px",
    mobilesvgWidth: "17px",
  },

  {
    divStyle: "absolute bottom-[9%] right-[41%]  ",
    bottom: "17%",
    left: "44%",
    imgStyle: "img-responsive",
    imgHeight: 25,
    imgWidth: 25,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "22px",
    svgWidth: "29px",
    mobilesvgHeight: "9px",
    mobilesvgWidth: "17px",
  },

  {
    divStyle: "absolute bottom-[16%] left-[25%] ",
    bottom: "17%",
    right: "44%",
    imgStyle: "img-responsive",
    imgHeight: 25,
    imgWidth: 25,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "22px",
    svgWidth: "29px",
    mobilesvgHeight: "9px",
    mobilesvgWidth: "17px",
  },

  {
    divStyle: "absolute bottom-[15%] right-[27%] ",
    bottom: "22%",
    right: "36%",
    imgStyle: "img-responsive",
    imgHeight: 25,
    imgWidth: 25,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "22px",
    svgWidth: "29px",
    mobilesvgHeight: "9px",
    mobilesvgWidth: "17px",
  },

 

  {
    divStyle: "absolute bottom-[40%] right-[10%]",
    bottom: "31%",
    right: "30%",
    imgStyle: "img-responsive",
    imgHeight: 25,
    imgWidth: 25,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "22px",
    svgWidth: "29px",
    mobilesvgHeight: "9px",
    mobilesvgWidth: "17px",
  },

  {
    divStyle: "absolute bottom-[25%] right-[16%] ",
    bottom: "41%",
    right: "26%",
    imgStyle: "img-responsive",
    imgHeight: 25,
    imgWidth: 25,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "22px",
    svgWidth: "29px",
    mobilesvgHeight: "9px",
    mobilesvgWidth: "17px",
  },

  // level 5

  {
    divStyle: "absolute top-[43%] left-[0%]",
    top: "44%",
    left: "22%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute top-[33%] left-[2%]",
    top: "37%",
    left: "23%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute top-[26%] left-[5%]  ",
    top: "31%",
    left: "25%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute top-[18%] left-[11%]",
    top: "25%",
    left: "28%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute ",
    top: "19%",
    left: "32%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute top-[12%] left-[16%]",
    top: "15%",
    left: "36%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute top-[2%] left-[34%]",
    top: "12%",
    left: "41%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },
  {
    divStyle: "absolute top-[0%] left-[45%]",
    top: "11%",
    left: "46%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute top-[0%] right-[45%]",
    top: "11%",
    right: "46%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute top-[6%] left-[25%]",
    top: "12%",
    right: "41%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },
  {
    divStyle: "absolute top-[6%] right-[25%]",
    top: "15%",
    right: "36%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute top-[12%] right-[17%]",
    top: "19%",
    right: "32%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute top-[18%] right-[11%]",
    top: "25%",
    right: "28%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute top-[26%] right-[6%] ",
    top: "31%",
    right: "25%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute top-[33%] right-[3%]",
    top: "37%",
    right: "23%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute top-[43%] right-[1%]",
    top: "44%",
    right: "22%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },
  //bottom level 5

  {
    divStyle: "absolute  bottom-[43%] left-[0%]  ",
    bottom: "44%",
    left: "22%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute  bottom-[33%] left-[2%]",
    bottom: "37%",
    left: "23%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute  bottom-[26%] left-[5%]  ",
    bottom: "31%",
    left: "25%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute  bottom-[18%] left-[11%]  ",
    bottom: "25%",
    left: "28%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute  bottom-[13%] left-[16%]  ",
    bottom: "19%",
    left: "32%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute  bottom-[6%] left-[25%]",
    bottom: "15%",
    left: "36%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute  bottom-[3%] left-[34%]  ",
    bottom: "12%",
    left: "41%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute  bottom-[1%] left-[45%]",
    bottom: "11%",
    left: "46%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute  bottom-[1%] right-[45%]",
    bottom: "11%",
    right: "46%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute  bottom-[3%] right-[34%]  ",
    bottom: "12%",
    right: "41%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute  bottom-[6%] right-[26%]",
    bottom: "15%",
    right: "36%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute  bottom-[13%] right-[18%]  ",
    bottom: "19%",
    right: "32%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute  bottom-[18%] right-[11%]  ",
    bottom: "25%",
    right: "28%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute  bottom-[26%] right-[5%]  ",
    bottom: "31%",
    right: "25%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute  bottom-[33%] right-[3%]",
    bottom: "37%",
    right: "23%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },

  {
    divStyle: "absolute  bottom-[43%] right-[1%]  ",
    bottom: "45%",
    right: "22%",
    imgStyle: "img-responsive2",
    imgHeight: 10,
    imgWidth: 10,
    emptyHeight: 18,
    emptyWidth: 18,
    svgHeight: "16px",
    svgWidth: "24px",
    mobilesvgHeight: "6px",
    mobilesvgWidth: "14px",
  },
];
